/**
 * Causeway · canonical sources registry.
 *
 * Single source of truth for every external citation. The <Cite id="…"/>
 * component looks up entries here and renders them consistently across
 * L3 sources rails and tutor responses. The `scripts/check-sources.mjs`
 * script HEAD-requests every URL and reports broken links.
 *
 * Authoring rule: every new source gets a stable kebab-case id and a
 * preferred URL (canonical landing page, not a PDF deep link). DOIs are
 * preferred for academic papers.
 */
export type SourceKind =
  | "primary"   // statute, executive order, central bank release
  | "academic"  // peer-reviewed paper or book
  | "report"    // think-tank, official agency, central bank working paper
  | "journalism"// established outlet
  | "data";     // FRED series, BLS table, BIS dataset

export interface Source {
  id: string;
  /** Author or originating organisation. */
  who: string;
  /** Work title. */
  title: string;
  /** Publication year, range, or "ongoing". */
  year: string;
  kind: SourceKind;
  /** Canonical landing-page URL. Required — every citation must resolve. */
  url: string;
  /** Optional DOI (without the doi.org prefix). */
  doi?: string;
}

export const SOURCES: Record<string, Source> = {
  "boe-money-creation-2014": {
    id: "boe-money-creation-2014",
    who: "Bank of England (McLeay, Radia & Thomas)",
    title: "Money creation in the modern economy",
    year: "2014",
    kind: "report",
    url: "https://www.bankofengland.co.uk/quarterly-bulletin/2014/q1/money-creation-in-the-modern-economy",
  },
  "mehrling-new-lombard-street-2011": {
    id: "mehrling-new-lombard-street-2011",
    who: "Perry Mehrling",
    title: "The New Lombard Street",
    year: "2011",
    kind: "academic",
    url: "https://press.princeton.edu/books/hardcover/9780691143989/the-new-lombard-street",
  },
  "bis-borio-financial-cycle-2014": {
    id: "bis-borio-financial-cycle-2014",
    who: "Claudio Borio (BIS)",
    title: "The financial cycle and macroeconomics: What have we learnt?",
    year: "2014",
    kind: "report",
    url: "https://www.bis.org/publ/work395.htm",
  },
  "fred-cpiaucsl": {
    id: "fred-cpiaucsl",
    who: "Federal Reserve Bank of St. Louis",
    title: "CPIAUCSL · CPI for All Urban Consumers",
    year: "ongoing",
    kind: "data",
    url: "https://fred.stlouisfed.org/series/CPIAUCSL",
  },
  "fred-fedfunds": {
    id: "fred-fedfunds",
    who: "Federal Reserve Bank of St. Louis",
    title: "FEDFUNDS · Effective Federal Funds Rate",
    year: "ongoing",
    kind: "data",
    url: "https://fred.stlouisfed.org/series/FEDFUNDS",
  },
  "fred-unrate": {
    id: "fred-unrate",
    who: "Federal Reserve Bank of St. Louis",
    title: "UNRATE · U-3 Unemployment Rate",
    year: "ongoing",
    kind: "data",
    url: "https://fred.stlouisfed.org/series/UNRATE",
  },
  "fred-drtscilm": {
    id: "fred-drtscilm",
    who: "Federal Reserve Bank of St. Louis",
    title: "DRTSCILM · SLOOS net % tightening C&I, large + middle firms",
    year: "ongoing",
    kind: "data",
    url: "https://fred.stlouisfed.org/series/DRTSCILM",
  },
  "fed-monetary-policy-report": {
    id: "fed-monetary-policy-report",
    who: "Federal Reserve Board",
    title: "Monetary Policy Report",
    year: "semi-annual",
    kind: "primary",
    url: "https://www.federalreserve.gov/monetarypolicy/mpr_default.htm",
  },
  "civil-rights-act-1964": {
    id: "civil-rights-act-1964",
    who: "US Congress",
    title: "Civil Rights Act of 1964 (Public Law 88-352)",
    year: "1964",
    kind: "primary",
    url: "https://www.govinfo.gov/app/details/STATUTE-78/STATUTE-78-Pg241",
  },

  /* ---------- FRED data series ----------
   * Pattern: https://fred.stlouisfed.org/series/<SYMBOL>. Stable for the
   * series symbols themselves; the human-readable name on the page can shift.
   */
  "fred-gdpc1": {
    id: "fred-gdpc1",
    who: "Federal Reserve Bank of St. Louis",
    title: "GDPC1 · Real Gross Domestic Product",
    year: "ongoing",
    kind: "data",
    url: "https://fred.stlouisfed.org/series/GDPC1",
  },
  "fred-m2sl": {
    id: "fred-m2sl",
    who: "Federal Reserve Bank of St. Louis",
    title: "M2SL · M2 Money Stock",
    year: "ongoing",
    kind: "data",
    url: "https://fred.stlouisfed.org/series/M2SL",
  },
  "fred-bogmbase": {
    id: "fred-bogmbase",
    who: "Federal Reserve Bank of St. Louis",
    title: "BOGMBASE · Monetary Base, Total",
    year: "ongoing",
    kind: "data",
    url: "https://fred.stlouisfed.org/series/BOGMBASE",
  },
  "fred-dgs10": {
    id: "fred-dgs10",
    who: "Federal Reserve Bank of St. Louis",
    title: "DGS10 · 10-Year Treasury Constant Maturity Rate",
    year: "ongoing",
    kind: "data",
    url: "https://fred.stlouisfed.org/series/DGS10",
  },
  "fred-dgs2": {
    id: "fred-dgs2",
    who: "Federal Reserve Bank of St. Louis",
    title: "DGS2 · 2-Year Treasury Constant Maturity Rate",
    year: "ongoing",
    kind: "data",
    url: "https://fred.stlouisfed.org/series/DGS2",
  },
  "fred-pcepi": {
    id: "fred-pcepi",
    who: "Federal Reserve Bank of St. Louis",
    title: "PCEPI · Personal Consumption Expenditures Price Index",
    year: "ongoing",
    kind: "data",
    url: "https://fred.stlouisfed.org/series/PCEPI",
  },
  "fred-mortgage30us": {
    id: "fred-mortgage30us",
    who: "Federal Reserve Bank of St. Louis",
    title: "MORTGAGE30US · 30-Year Fixed Rate Mortgage Average",
    year: "ongoing",
    kind: "data",
    url: "https://fred.stlouisfed.org/series/MORTGAGE30US",
  },
  "fred-dtwexbgs": {
    id: "fred-dtwexbgs",
    who: "Federal Reserve Bank of St. Louis",
    title: "DTWEXBGS · Trade-Weighted US Dollar Index, Broad",
    year: "ongoing",
    kind: "data",
    url: "https://fred.stlouisfed.org/series/DTWEXBGS",
  },

  /* ---------- Federal Reserve publications ---------- */
  "fed-fomc-calendars": {
    id: "fed-fomc-calendars",
    who: "Federal Reserve Board",
    title: "FOMC calendars, statements, projections",
    year: "ongoing",
    kind: "primary",
    url: "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm",
  },
  "fed-survey-consumer-finances": {
    id: "fed-survey-consumer-finances",
    who: "Federal Reserve Board",
    title: "Survey of Consumer Finances",
    year: "triennial",
    kind: "data",
    url: "https://www.federalreserve.gov/econres/scfindex.htm",
  },
  "fed-h41-balance-sheet": {
    id: "fed-h41-balance-sheet",
    who: "Federal Reserve Board",
    title: "H.4.1 · Factors Affecting Reserve Balances",
    year: "weekly",
    kind: "data",
    url: "https://www.federalreserve.gov/releases/h41/",
  },
  "fed-h10-fx-rates": {
    id: "fed-h10-fx-rates",
    who: "Federal Reserve Board",
    title: "H.10 · Foreign Exchange Rates",
    year: "weekly",
    kind: "data",
    url: "https://www.federalreserve.gov/releases/h10/",
  },

  /* ---------- Regional Federal Reserve banks ---------- */
  "cleveland-fed-inflation-expectations": {
    id: "cleveland-fed-inflation-expectations",
    who: "Federal Reserve Bank of Cleveland",
    title: "Inflation expectations dashboard",
    year: "ongoing",
    kind: "data",
    url: "https://www.clevelandfed.org/indicators-and-data/inflation-expectations",
  },
  "nyfed-household-debt": {
    id: "nyfed-household-debt",
    who: "Federal Reserve Bank of New York",
    title: "Quarterly Report on Household Debt and Credit",
    year: "quarterly",
    kind: "report",
    url: "https://www.newyorkfed.org/microeconomics/hhdc",
  },
  "dallas-fed-trimmed-pce": {
    id: "dallas-fed-trimmed-pce",
    who: "Federal Reserve Bank of Dallas",
    title: "Trimmed Mean PCE Inflation Rate",
    year: "ongoing",
    kind: "data",
    url: "https://www.dallasfed.org/research/pce",
  },

  /* ---------- BLS / BEA ---------- */
  "bls-cpi": {
    id: "bls-cpi",
    who: "US Bureau of Labor Statistics",
    title: "Consumer Price Index home",
    year: "ongoing",
    kind: "data",
    url: "https://www.bls.gov/cpi/",
  },
  "bls-ces": {
    id: "bls-ces",
    who: "US Bureau of Labor Statistics",
    title: "Current Employment Statistics (CES)",
    year: "ongoing",
    kind: "data",
    url: "https://www.bls.gov/ces/",
  },
  "bls-cps": {
    id: "bls-cps",
    who: "US Bureau of Labor Statistics",
    title: "Current Population Survey · Employment Situation",
    year: "ongoing",
    kind: "data",
    url: "https://www.bls.gov/cps/",
  },
  "bea-nipa": {
    id: "bea-nipa",
    who: "US Bureau of Economic Analysis",
    title: "National Income and Product Accounts (NIPA)",
    year: "ongoing",
    kind: "data",
    url: "https://www.bea.gov/resources/methodologies/nipa-handbook",
  },
  "bea-international-transactions": {
    id: "bea-international-transactions",
    who: "US Bureau of Economic Analysis",
    title: "International Transactions Accounts",
    year: "ongoing",
    kind: "data",
    url: "https://www.bea.gov/data/intl-trade-investment/international-transactions",
  },

  /* ---------- BIS ---------- */
  "bis-annual-economic-report": {
    id: "bis-annual-economic-report",
    who: "Bank for International Settlements",
    title: "Annual Economic Report",
    year: "annual",
    kind: "report",
    url: "https://www.bis.org/publ/arpdf/ar2024e.htm",
  },
  "bis-triennial-fx-survey": {
    id: "bis-triennial-fx-survey",
    who: "Bank for International Settlements",
    title: "Triennial Central Bank Survey of FX and OTC derivatives markets",
    year: "ongoing",
    kind: "data",
    url: "https://www.bis.org/statistics/rpfx22.htm",
  },
  "bis-cbdc-hub": {
    id: "bis-cbdc-hub",
    who: "Bank for International Settlements",
    title: "Innovation Hub · CBDC project work",
    year: "ongoing",
    kind: "report",
    url: "https://www.bis.org/about/bisih/topics/cbdc.htm",
  },

  /* ---------- IMF ---------- */
  "imf-weo": {
    id: "imf-weo",
    who: "International Monetary Fund",
    title: "World Economic Outlook",
    year: "biannual",
    kind: "report",
    url: "https://www.imf.org/en/Publications/WEO",
  },
  "imf-gfsr": {
    id: "imf-gfsr",
    who: "International Monetary Fund",
    title: "Global Financial Stability Report",
    year: "biannual",
    kind: "report",
    url: "https://www.imf.org/en/Publications/GFSR",
  },
  "imf-fiscal-monitor": {
    id: "imf-fiscal-monitor",
    who: "International Monetary Fund",
    title: "Fiscal Monitor",
    year: "biannual",
    kind: "report",
    url: "https://www.imf.org/en/Publications/FM",
  },
  "imf-external-sector-report": {
    id: "imf-external-sector-report",
    who: "International Monetary Fund",
    title: "External Sector Report",
    year: "annual",
    kind: "report",
    url: "https://www.imf.org/en/Publications/ESR",
  },
  "imf-cofer": {
    id: "imf-cofer",
    who: "International Monetary Fund",
    title: "COFER · Currency Composition of Official Foreign Exchange Reserves",
    year: "quarterly",
    kind: "data",
    url: "https://data.imf.org/COFER",
  },

  /* ---------- WTO / OECD / World Bank ---------- */
  "wto-world-trade-report": {
    id: "wto-world-trade-report",
    who: "World Trade Organization",
    title: "World Trade Report",
    year: "annual",
    kind: "report",
    url: "https://www.wto.org/english/res_e/publications_e/wtr_e.htm",
  },
  "wto-annual-reports": {
    id: "wto-annual-reports",
    who: "World Trade Organization",
    title: "Annual Reports",
    year: "annual",
    kind: "report",
    url: "https://www.wto.org/english/res_e/reser_e/annual_report_e.htm",
  },
  /* ---------- Policy research outfits ---------- */
  "piie-bown-tariff-tracker": {
    id: "piie-bown-tariff-tracker",
    who: "Peterson Institute for International Economics (Chad Bown)",
    title: "US-China Trade War Tariffs · An Up-to-Date Chart",
    year: "ongoing",
    kind: "report",
    url: "https://www.piie.com/research/piie-charts/2019/us-china-trade-war-tariffs-date-chart",
  },
  "crs-section-301": {
    id: "crs-section-301",
    who: "Congressional Research Service",
    title: "Section 301 of the Trade Act of 1974",
    year: "2024",
    kind: "report",
    url: "https://crsreports.congress.gov/product/details?prodcode=IF11346",
  },
  "wid-database": {
    id: "wid-database",
    who: "World Inequality Lab",
    title: "World Inequality Database (WID.world)",
    year: "ongoing",
    kind: "data",
    url: "https://wid.world/",
  },
  "un-world-population-prospects": {
    id: "un-world-population-prospects",
    who: "United Nations · Department of Economic and Social Affairs",
    title: "World Population Prospects",
    year: "biennial",
    kind: "data",
    url: "https://population.un.org/wpp/",
  },

  /* ---------- Foundational books with publisher pages ---------- */
  "reinhart-rogoff-this-time-different-2009": {
    id: "reinhart-rogoff-this-time-different-2009",
    who: "Carmen Reinhart & Kenneth Rogoff",
    title: "This Time is Different: Eight Centuries of Financial Folly",
    year: "2009",
    kind: "academic",
    url: "https://press.princeton.edu/books/paperback/9780691152646/this-time-is-different",
  },
  "shiller-irrational-exuberance": {
    id: "shiller-irrational-exuberance",
    who: "Robert J. Shiller",
    title: "Irrational Exuberance",
    year: "2000 / 2015",
    kind: "academic",
    url: "https://press.princeton.edu/books/paperback/9780691173122/irrational-exuberance",
  },
  "tooze-crashed-2018": {
    id: "tooze-crashed-2018",
    who: "Adam Tooze",
    title: "Crashed: How a Decade of Financial Crises Changed the World",
    year: "2018",
    kind: "academic",
    url: "https://www.penguinrandomhouse.com/books/315376/crashed-by-adam-tooze/",
  },
  "pistor-code-of-capital-2019": {
    id: "pistor-code-of-capital-2019",
    who: "Katharina Pistor",
    title: "The Code of Capital",
    year: "2019",
    kind: "academic",
    url: "https://press.princeton.edu/books/hardcover/9780691178974/the-code-of-capital",
  },
  "graeber-debt-2011": {
    id: "graeber-debt-2011",
    who: "David Graeber",
    title: "Debt: The First 5,000 Years",
    year: "2011",
    kind: "academic",
    url: "https://www.mhpbooks.com/books/debt/",
  },
  "minsky-stabilizing-unstable-economy": {
    id: "minsky-stabilizing-unstable-economy",
    who: "Hyman P. Minsky",
    title: "Stabilizing an Unstable Economy",
    year: "1986",
    kind: "academic",
    url: "https://www.mhprofessional.com/9780071592994-usa-stabilizing-an-unstable-economy",
  },

  /* ---------- Academic papers (DOI / NBER / journal) ---------- */
  "friedman-role-of-monetary-policy-1968": {
    id: "friedman-role-of-monetary-policy-1968",
    who: "Milton Friedman",
    title: "The Role of Monetary Policy",
    year: "1968",
    kind: "academic",
    url: "https://www.jstor.org/stable/1831652",
  },
  "hayek-use-of-knowledge-1945": {
    id: "hayek-use-of-knowledge-1945",
    who: "Friedrich Hayek",
    title: "The Use of Knowledge in Society",
    year: "1945",
    kind: "academic",
    url: "https://www.jstor.org/stable/1809376",
  },
  "yermack-bitcoin-real-currency-2013": {
    id: "yermack-bitcoin-real-currency-2013",
    who: "David Yermack",
    title: "Is Bitcoin a Real Currency? An Economic Appraisal (NBER WP 19747)",
    year: "2013",
    kind: "academic",
    url: "https://www.nber.org/papers/w19747",
  },
  "schularick-taylor-credit-booms-2012": {
    id: "schularick-taylor-credit-booms-2012",
    who: "Moritz Schularick & Alan M. Taylor",
    title: "Credit Booms Gone Bust: Monetary Policy, Leverage Cycles, and Financial Crises, 1870–2008",
    year: "2012",
    kind: "academic",
    url: "https://www.aeaweb.org/articles?id=10.1257/aer.102.2.1029",
  },

  /* ---------- Foundational primary sources ---------- */
  "nakamoto-bitcoin-2008": {
    id: "nakamoto-bitcoin-2008",
    who: "Satoshi Nakamoto",
    title: "Bitcoin: A Peer-to-Peer Electronic Cash System",
    year: "2008",
    kind: "primary",
    url: "https://bitcoin.org/bitcoin.pdf",
  },

  /* ---------- Round-2 backfill (v0.5): high-recognition books + papers ---------- */
  "kahneman-thinking-fast-slow-2011": {
    id: "kahneman-thinking-fast-slow-2011",
    who: "Daniel Kahneman",
    title: "Thinking, Fast and Slow",
    year: "2011",
    kind: "academic",
    url: "https://us.macmillan.com/books/9780374533557/thinkingfastandslow/",
  },
  "eichengreen-exorbitant-privilege-2011": {
    id: "eichengreen-exorbitant-privilege-2011",
    who: "Barry Eichengreen",
    title: "Exorbitant Privilege: The Rise and Fall of the Dollar",
    year: "2011",
    kind: "academic",
    url: "https://global.oup.com/academic/product/exorbitant-privilege-9780199931095",
  },
  "piketty-capital-21st-century-2013": {
    id: "piketty-capital-21st-century-2013",
    who: "Thomas Piketty",
    title: "Capital in the Twenty-First Century",
    year: "2013",
    kind: "academic",
    url: "https://www.hup.harvard.edu/books/9780674430006",
  },
  "milanovic-global-inequality-2016": {
    id: "milanovic-global-inequality-2016",
    who: "Branko Milanovic",
    title: "Global Inequality: A New Approach for the Age of Globalization",
    year: "2016",
    kind: "academic",
    url: "https://www.hup.harvard.edu/books/9780674984035",
  },
  "goodhart-pradhan-demographic-reversal-2020": {
    id: "goodhart-pradhan-demographic-reversal-2020",
    who: "Charles Goodhart & Manoj Pradhan",
    title: "The Great Demographic Reversal",
    year: "2020",
    kind: "academic",
    url: "https://link.springer.com/book/10.1007/978-3-030-42657-6",
  },
  "steil-battle-of-bretton-woods-2013": {
    id: "steil-battle-of-bretton-woods-2013",
    who: "Benn Steil",
    title: "The Battle of Bretton Woods",
    year: "2013",
    kind: "academic",
    url: "https://press.princeton.edu/books/paperback/9780691162379/the-battle-of-bretton-woods",
  },
  "lewis-big-short-2010": {
    id: "lewis-big-short-2010",
    who: "Michael Lewis",
    title: "The Big Short: Inside the Doomsday Machine",
    year: "2010",
    kind: "journalism",
    url: "https://wwnorton.com/books/9780393338829",
  },
  "gorton-slapped-invisible-hand-2010": {
    id: "gorton-slapped-invisible-hand-2010",
    who: "Gary B. Gorton",
    title: "Slapped by the Invisible Hand: The Panic of 2007",
    year: "2010",
    kind: "academic",
    url: "https://global.oup.com/academic/product/slapped-by-the-invisible-hand-9780199734153",
  },
  "bogle-little-book-common-sense-2007": {
    id: "bogle-little-book-common-sense-2007",
    who: "John C. Bogle",
    title: "The Little Book of Common Sense Investing",
    year: "2007",
    kind: "academic",
    url: "https://www.wiley.com/en-us/The+Little+Book+of+Common+Sense+Investing%3A+The+Only+Way+to+Guarantee+Your+Fair+Share+of+Stock+Market+Returns%2C+Updated+and+Revised-p-9781119404514",
  },
  "friedman-schwartz-monetary-history-1963": {
    id: "friedman-schwartz-monetary-history-1963",
    who: "Milton Friedman & Anna J. Schwartz",
    title: "A Monetary History of the United States, 1867-1960",
    year: "1963",
    kind: "academic",
    url: "https://press.princeton.edu/books/paperback/9780691003542/a-monetary-history-of-the-united-states-1867-1960",
  },
  "coyle-gdp-affectionate-history-2014": {
    id: "coyle-gdp-affectionate-history-2014",
    who: "Diane Coyle",
    title: "GDP: A Brief but Affectionate History",
    year: "2014",
    kind: "academic",
    url: "https://press.princeton.edu/books/paperback/9780691169859/gdp",
  },
  "autor-dorn-hanson-china-syndrome-2013": {
    id: "autor-dorn-hanson-china-syndrome-2013",
    who: "David H. Autor, David Dorn & Gordon H. Hanson",
    title: "The China Syndrome: Local Labor Market Effects of Import Competition",
    year: "2013",
    kind: "academic",
    url: "https://www.aeaweb.org/articles?id=10.1257/aer.103.6.2121",
  },
  "akerlof-market-for-lemons-1970": {
    id: "akerlof-market-for-lemons-1970",
    who: "George A. Akerlof",
    title: "The Market for 'Lemons': Quality Uncertainty and the Market Mechanism",
    year: "1970",
    kind: "academic",
    url: "https://www.jstor.org/stable/1879431",
  },
  "coase-problem-of-social-cost-1960": {
    id: "coase-problem-of-social-cost-1960",
    who: "Ronald H. Coase",
    title: "The Problem of Social Cost",
    year: "1960",
    kind: "academic",
    url: "https://www.law.uchicago.edu/lawecon/coaseinmemoriam/problemofsocialcost",
  },
  "fama-efficient-capital-markets-1970": {
    id: "fama-efficient-capital-markets-1970",
    who: "Eugene F. Fama",
    title: "Efficient Capital Markets: A Review of Theory and Empirical Work",
    year: "1970",
    kind: "academic",
    url: "https://www.jstor.org/stable/2325486",
  },

  /* ---------- Round-3 backfill (v0.7): more verified TIER 2 ---------- */
  "mian-sufi-house-of-debt-2014": {
    id: "mian-sufi-house-of-debt-2014",
    who: "Atif Mian & Amir Sufi",
    title: "House of Debt",
    year: "2014",
    kind: "academic",
    url: "https://press.uchicago.edu/ucp/books/book/chicago/H/bo20832545.html",
  },
  "rodrik-globalization-paradox-2011": {
    id: "rodrik-globalization-paradox-2011",
    who: "Dani Rodrik",
    title: "The Globalization Paradox: Democracy and the Future of the World Economy",
    year: "2011",
    kind: "academic",
    url: "https://wwnorton.com/books/The-Globalization-Paradox/",
  },
  "prasad-future-of-money-2021": {
    id: "prasad-future-of-money-2021",
    who: "Eswar S. Prasad",
    title: "The Future of Money",
    year: "2021",
    kind: "academic",
    url: "https://www.hup.harvard.edu/books/9780674258440",
  },
  "ilmanen-expected-returns-2011": {
    id: "ilmanen-expected-returns-2011",
    who: "Antti Ilmanen",
    title: "Expected Returns: An Investor's Guide to Harvesting Market Rewards",
    year: "2011",
    kind: "academic",
    url: "https://www.wiley.com/en-us/Expected+Returns%3A+An+Investor%27s+Guide+to+Harvesting+Market+Rewards-p-9781119990772",
  },
  "king-end-of-alchemy-2016": {
    id: "king-end-of-alchemy-2016",
    who: "Mervyn King",
    title: "The End of Alchemy: Money, Banking, and the Future of the Global Economy",
    year: "2016",
    kind: "academic",
    url: "https://wwnorton.com/books/The-End-of-Alchemy",
  },
  "glaeser-triumph-of-city-2011": {
    id: "glaeser-triumph-of-city-2011",
    who: "Edward L. Glaeser",
    title: "Triumph of the City",
    year: "2011",
    kind: "academic",
    url: "https://www.penguinrandomhouse.com/books/303439/triumph-of-the-city-by-edward-glaeser/",
  },
  "galbraith-short-history-financial-euphoria-1990": {
    id: "galbraith-short-history-financial-euphoria-1990",
    who: "John Kenneth Galbraith",
    title: "A Short History of Financial Euphoria",
    year: "1990",
    kind: "academic",
    url: "https://www.penguinrandomhouse.com/books/321392/a-short-history-of-financial-euphoria-by-john-kenneth-galbraith/",
  },
  "bernanke-geithner-paulson-firefighting-2019": {
    id: "bernanke-geithner-paulson-firefighting-2019",
    who: "Ben S. Bernanke, Timothy F. Geithner & Henry M. Paulson, Jr.",
    title: "Firefighting: The Financial Crisis and Its Lessons",
    year: "2019",
    kind: "academic",
    url: "https://www.penguinrandomhouse.com/books/608388/firefighting-by-ben-s-bernanke-timothy-f-geithner-and-henry-m-paulson-jr/",
  },
  "dalio-changing-world-order-2021": {
    id: "dalio-changing-world-order-2021",
    who: "Ray Dalio",
    title: "Principles for Dealing with the Changing World Order",
    year: "2021",
    kind: "academic",
    url: "https://www.simonandschuster.com/books/Principles-for-Dealing-with-the-Changing-World-Order/Ray-Dalio/Principles/9781982160272",
  },
  "subramanian-eclipse-2011": {
    id: "subramanian-eclipse-2011",
    who: "Arvind Subramanian",
    title: "Eclipse: Living in the Shadow of China's Economic Dominance",
    year: "2011",
    kind: "report",
    url: "https://www.piie.com/bookstore/eclipse-living-shadow-chinas-economic-dominance",
  },
  "drezner-united-states-of-sanctions-2021": {
    id: "drezner-united-states-of-sanctions-2021",
    who: "Daniel W. Drezner",
    title: "The United States of Sanctions: The Use and Abuse of Economic Coercion",
    year: "2021",
    kind: "journalism",
    url: "https://www.foreignaffairs.com/articles/united-states/2021-08-24/united-states-sanctions",
  },
  "sandel-what-money-cant-buy-2012": {
    id: "sandel-what-money-cant-buy-2012",
    who: "Michael J. Sandel",
    title: "What Money Can't Buy: The Moral Limits of Markets",
    year: "2012",
    kind: "academic",
    url: "https://us.macmillan.com/books/9780374533656/whatmoneycantbuy/",
  },
  "tucker-unelected-power-2018": {
    id: "tucker-unelected-power-2018",
    who: "Paul Tucker",
    title: "Unelected Power: The Quest for Legitimacy in Central Banking and the Regulatory State",
    year: "2018",
    kind: "academic",
    url: "https://press.princeton.edu/books/paperback/9780691196305/unelected-power",
  },
  "hudson-forgive-them-their-debts-2018": {
    id: "hudson-forgive-them-their-debts-2018",
    who: "Michael Hudson",
    title: "...and forgive them their debts: Lending, Foreclosure and Redemption from Bronze Age Finance to the Jubilee Year",
    year: "2018",
    kind: "academic",
    url: "https://michael-hudson.com/2018/08/and-forgive-them-their-debts/",
  },
  "volcker-keeping-at-it-2018": {
    id: "volcker-keeping-at-it-2018",
    who: "Paul A. Volcker (with Christine Harper)",
    title: "Keeping At It: The Quest for Sound Money and Good Government",
    year: "2018",
    kind: "academic",
    url: "https://www.hachettebookgroup.com/titles/paul-a-volcker/keeping-at-it/9781541788299/",
  },
  "zarate-treasurys-war-2013": {
    id: "zarate-treasurys-war-2013",
    who: "Juan Zarate",
    title: "Treasury's War: The Unleashing of a New Era of Financial Warfare",
    year: "2013",
    kind: "journalism",
    url: "https://www.hachettebookgroup.com/titles/juan-zarate/treasurys-war/9781610391160/",
  },
  "pettis-klein-trade-wars-class-wars-2020": {
    id: "pettis-klein-trade-wars-class-wars-2020",
    who: "Matthew C. Klein & Michael Pettis",
    title: "Trade Wars Are Class Wars: How Rising Inequality Distorts the Global Economy",
    year: "2020",
    kind: "academic",
    url: "https://yalebooks.yale.edu/book/9780300261448/trade-wars-are-class-wars/",
  },

  /* ---------- Round-4 backfill (v0.7 wrap): remaining TIER 2 stragglers ---------- */
  "kindleberger-aliber-manias-panics-crashes-2015": {
    id: "kindleberger-aliber-manias-panics-crashes-2015",
    who: "Charles P. Kindleberger & Robert Z. Aliber",
    title: "Manias, Panics, and Crashes: A History of Financial Crises (7th ed.)",
    year: "2015",
    kind: "academic",
    url: "https://link.springer.com/book/10.1007/978-1-137-52574-1",
  },
  "reinhart-rogoff-growth-in-time-of-debt-2010": {
    id: "reinhart-rogoff-growth-in-time-of-debt-2010",
    who: "Carmen M. Reinhart & Kenneth S. Rogoff",
    title: "Growth in a Time of Debt",
    year: "2010",
    kind: "academic",
    url: "https://www.aeaweb.org/articles?id=10.1257/aer.100.2.573",
  },
  "mankiw-small-menu-costs-1985": {
    id: "mankiw-small-menu-costs-1985",
    who: "N. Gregory Mankiw",
    title: "Small Menu Costs and Large Business Cycles: A Macroeconomic Model of Monopoly",
    year: "1985",
    kind: "academic",
    url: "https://academic.oup.com/qje/article-abstract/100/2/529/1844809",
  },
  "sheffi-resilient-enterprise-2005": {
    id: "sheffi-resilient-enterprise-2005",
    who: "Yossi Sheffi",
    title: "The Resilient Enterprise: Overcoming Vulnerability for Competitive Advantage",
    year: "2005",
    kind: "academic",
    url: "https://mitpress.mit.edu/9780262693493/the-resilient-enterprise/",
  },
  "kuznets-national-income-1934": {
    id: "kuznets-national-income-1934",
    who: "Simon Kuznets",
    title: "National Income, 1929-1932",
    year: "1934",
    kind: "academic",
    url: "https://www.nber.org/books-and-chapters/national-income-1929-1932/national-income-1929-1932",
  },
  "iea-world-energy-outlook": {
    id: "iea-world-energy-outlook",
    who: "International Energy Agency",
    title: "World Energy Outlook",
    year: "annual",
    kind: "report",
    url: "https://www.iea.org/reports/world-energy-outlook-2024",
  },

  /* ---------- Round-5 backfill (v0.7 final): classical works + academic papers ---------- */
  "marshall-principles-economics-1890": {
    id: "marshall-principles-economics-1890",
    who: "Alfred Marshall",
    title: "Principles of Economics",
    year: "1890",
    kind: "academic",
    url: "https://oll.libertyfund.org/titles/marshall-principles-of-economics-8th-ed",
  },
  "ricardo-principles-political-economy-1817": {
    id: "ricardo-principles-political-economy-1817",
    who: "David Ricardo",
    title: "On the Principles of Political Economy and Taxation",
    year: "1817",
    kind: "academic",
    url: "https://oll.libertyfund.org/titles/ricardo-the-works-and-correspondence-of-david-ricardo-vol-1-principles-of-political-economy-and-taxation",
  },
  "pigou-economics-of-welfare-1920": {
    id: "pigou-economics-of-welfare-1920",
    who: "Arthur Cecil Pigou",
    title: "The Economics of Welfare",
    year: "1920",
    kind: "academic",
    url: "https://oll.libertyfund.org/titles/pigou-the-economics-of-welfare",
  },
  "hume-essays-1752": {
    id: "hume-essays-1752",
    who: "David Hume",
    title: "Essays, Moral, Political, and Literary (incl. 'Of the Balance of Trade')",
    year: "1752",
    kind: "academic",
    url: "https://oll.libertyfund.org/pages/hume-s-essays",
  },
  "list-national-system-1841": {
    id: "list-national-system-1841",
    who: "Friedrich List",
    title: "The National System of Political Economy",
    year: "1841",
    kind: "academic",
    url: "https://oll.libertyfund.org/titles/lloyd-the-national-system-of-political-economy",
  },
  "mackay-extraordinary-popular-delusions-1841": {
    id: "mackay-extraordinary-popular-delusions-1841",
    who: "Charles Mackay",
    title: "Memoirs of Extraordinary Popular Delusions and the Madness of Crowds",
    year: "1841",
    kind: "academic",
    url: "https://www.gutenberg.org/ebooks/24518",
  },
  "rey-dilemma-not-trilemma-2015": {
    id: "rey-dilemma-not-trilemma-2015",
    who: "Hélène Rey",
    title: "Dilemma not Trilemma: The Global Financial Cycle and Monetary Policy Independence (NBER WP 21162)",
    year: "2015",
    kind: "academic",
    url: "https://www.nber.org/papers/w21162",
  },
  "nber-business-cycle-dating": {
    id: "nber-business-cycle-dating",
    who: "National Bureau of Economic Research",
    title: "Business Cycle Dating Committee",
    year: "ongoing",
    kind: "report",
    url: "https://www.nber.org/research/business-cycle-dating",
  },
  "romer-romer-monetary-shocks-2004": {
    id: "romer-romer-monetary-shocks-2004",
    who: "Christina D. Romer & David H. Romer",
    title: "A New Measure of Monetary Shocks: Derivation and Implications",
    year: "2004",
    kind: "academic",
    url: "https://www.aeaweb.org/articles?id=10.1257/0002828042002651",
  },
  "kydland-prescott-time-to-build-1982": {
    id: "kydland-prescott-time-to-build-1982",
    who: "Finn E. Kydland & Edward C. Prescott",
    title: "Time to Build and Aggregate Fluctuations",
    year: "1982",
    kind: "academic",
    url: "https://www.econometricsociety.org/publications/econometrica/1982/11/01/time-build-and-aggregate-fluctuations",
  },
  "phelps-money-wage-dynamics-1968": {
    id: "phelps-money-wage-dynamics-1968",
    who: "Edmund S. Phelps",
    title: "Money-Wage Dynamics and Labor-Market Equilibrium",
    year: "1968",
    kind: "academic",
    url: "https://www.jstor.org/stable/1830370",
  },
  "frey-osborne-future-of-employment-2013": {
    id: "frey-osborne-future-of-employment-2013",
    who: "Carl Benedikt Frey & Michael A. Osborne",
    title: "The Future of Employment: How Susceptible Are Jobs to Computerisation?",
    year: "2013",
    kind: "academic",
    url: "https://www.oxfordmartin.ox.ac.uk/publications/the-future-of-employment",
  },

  /* ---------- Round 6: backfill from inline entries (2026-05) ----------
   * Promotes inline <Sources entries=[]> citations to the registry where a
   * stable canonical URL exists. The cases left inline after this round
   * (private research notes, vendor dashboards, bundle references like
   * "various") are genuinely thin — not lazy.
   */

  /* Classical canon */
  "innes-what-is-money-1913": {
    id: "innes-what-is-money-1913",
    who: "A. Mitchell Innes",
    title: "What is Money?",
    year: "1913",
    kind: "academic",
    url: "https://archive.org/details/jstor-1133275",
  },
  "knapp-state-theory-money-1905": {
    id: "knapp-state-theory-money-1905",
    who: "Georg Friedrich Knapp",
    title: "The State Theory of Money",
    year: "1905",
    kind: "academic",
    url: "https://archive.org/details/in.ernet.dli.2015.262593",
  },
  "walras-elements-pure-economics-1874": {
    id: "walras-elements-pure-economics-1874",
    who: "Léon Walras",
    title: "Elements of Pure Economics",
    year: "1874",
    kind: "academic",
    url: "https://archive.org/details/elementsofpureec0000walr",
  },
  "keynes-general-theory-1936": {
    id: "keynes-general-theory-1936",
    who: "John Maynard Keynes",
    title: "The General Theory of Employment, Interest, and Money",
    year: "1936",
    kind: "academic",
    url: "https://archive.org/details/in.ernet.dli.2015.262693",
  },
  "juglar-crises-commerciales-1862": {
    id: "juglar-crises-commerciales-1862",
    who: "Clément Juglar",
    title: "Des crises commerciales et de leur retour périodique",
    year: "1862",
    kind: "academic",
    url: "https://archive.org/search?query=juglar+crises+commerciales",
  },
  "kitchin-cycles-trends-1923": {
    id: "kitchin-cycles-trends-1923",
    who: "Joseph Kitchin",
    title: "Cycles and Trends in Economic Factors",
    year: "1923",
    kind: "academic",
    url: "https://www.jstor.org/stable/1927031",
  },
  "hamilton-report-on-manufactures-1791": {
    id: "hamilton-report-on-manufactures-1791",
    who: "Alexander Hamilton",
    title: "Report on the Subject of Manufactures",
    year: "1791",
    kind: "primary",
    url: "https://founders.archives.gov/documents/Hamilton/01-10-02-0001-0007",
  },
  "lorenz-concentration-of-wealth-1905": {
    id: "lorenz-concentration-of-wealth-1905",
    who: "Max O. Lorenz",
    title: "Methods of Measuring the Concentration of Wealth",
    year: "1905",
    kind: "academic",
    url: "https://www.jstor.org/stable/2276207",
  },
  "gini-variability-mutability-1912": {
    id: "gini-variability-mutability-1912",
    who: "Corrado Gini",
    title: "Variabilità e Mutabilità",
    year: "1912",
    kind: "academic",
    url: "https://archive.org/search?query=gini+variabilita+mutabilita",
  },
  "beveridge-full-employment-1944": {
    id: "beveridge-full-employment-1944",
    who: "William Beveridge",
    title: "Full Employment in a Free Society",
    year: "1944",
    kind: "academic",
    url: "https://archive.org/details/fullemploymentin0000beve",
  },

  /* FRED data series (round 6) */
  "fred-totbkcr": {
    id: "fred-totbkcr",
    who: "Federal Reserve Bank of St. Louis",
    title: "TOTBKCR · Bank Credit, All Commercial Banks",
    year: "ongoing",
    kind: "data",
    url: "https://fred.stlouisfed.org/series/TOTBKCR",
  },
  "fred-totresns": {
    id: "fred-totresns",
    who: "Federal Reserve Bank of St. Louis",
    title: "TOTRESNS · Reserves of Depository Institutions",
    year: "ongoing",
    kind: "data",
    url: "https://fred.stlouisfed.org/series/TOTRESNS",
  },
  "fred-usslind": {
    id: "fred-usslind",
    who: "Federal Reserve Bank of St. Louis / Philadelphia Fed",
    title: "USSLIND · Leading Index for the United States",
    year: "ongoing",
    kind: "data",
    url: "https://fred.stlouisfed.org/series/USSLIND",
  },
  "fred-t10y2y": {
    id: "fred-t10y2y",
    who: "Federal Reserve Bank of St. Louis",
    title: "T10Y2Y · 10-Year minus 2-Year Treasury Yield Spread",
    year: "ongoing",
    kind: "data",
    url: "https://fred.stlouisfed.org/series/T10Y2Y",
  },

  /* Federal Reserve / Treasury */
  "fed-reserve-requirements": {
    id: "fed-reserve-requirements",
    who: "Federal Reserve Board",
    title: "Reserve Requirements (policy page; 2020 cut to zero)",
    year: "2020",
    kind: "primary",
    url: "https://www.federalreserve.gov/monetarypolicy/reservereq.htm",
  },
  "fed-policy-implementation": {
    id: "fed-policy-implementation",
    who: "Federal Reserve Board",
    title: "Open Market Operations · Implementation (IOR / ON RRP regime)",
    year: "ongoing",
    kind: "primary",
    url: "https://www.federalreserve.gov/monetarypolicy/openmarket.htm",
  },
  "fed-money-and-payments-2022": {
    id: "fed-money-and-payments-2022",
    who: "Federal Reserve Board",
    title: "Money and Payments: The U.S. Dollar in the Age of Digital Transformation",
    year: "2022",
    kind: "primary",
    url: "https://www.federalreserve.gov/publications/money-and-payments-discussion-paper.htm",
  },
  "fed-fomc-calendars-sep": {
    id: "fed-fomc-calendars-sep",
    who: "Federal Reserve Board",
    title: "FOMC Meeting Calendars · Summary of Economic Projections (dot plot)",
    year: "ongoing",
    kind: "primary",
    url: "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm",
  },

  /* Government data */
  "bea-pce-price-index": {
    id: "bea-pce-price-index",
    who: "Bureau of Economic Analysis",
    title: "Personal Consumption Expenditures Price Index",
    year: "ongoing",
    kind: "data",
    url: "https://www.bea.gov/data/personal-consumption-expenditures-price-index",
  },
  "bea-consumer-spending": {
    id: "bea-consumer-spending",
    who: "Bureau of Economic Analysis",
    title: "Personal Consumption Expenditures (consumer spending data)",
    year: "ongoing",
    kind: "data",
    url: "https://www.bea.gov/data/consumer-spending/main",
  },
  "bls-jolts": {
    id: "bls-jolts",
    who: "Bureau of Labor Statistics",
    title: "Job Openings and Labor Turnover Survey (JOLTS)",
    year: "ongoing",
    kind: "data",
    url: "https://www.bls.gov/jlt/",
  },
  "cbo-budget-economic-outlook": {
    id: "cbo-budget-economic-outlook",
    who: "Congressional Budget Office",
    title: "The Budget and Economic Outlook (long-term projections)",
    year: "annual",
    kind: "primary",
    url: "https://www.cbo.gov/about/products/major-recurring-reports",
  },
  "fhfa-hpi": {
    id: "fhfa-hpi",
    who: "Federal Housing Finance Agency",
    title: "FHFA House Price Index",
    year: "1991–present",
    kind: "data",
    url: "https://www.fhfa.gov/data/hpi",
  },
  "ofac-sanctions-programs": {
    id: "ofac-sanctions-programs",
    who: "U.S. Treasury Office of Foreign Assets Control",
    title: "Sanctions Programs and Country Information",
    year: "ongoing",
    kind: "primary",
    url: "https://ofac.treasury.gov/sanctions-programs-and-country-information",
  },
  "fcic-financial-crisis-report-2011": {
    id: "fcic-financial-crisis-report-2011",
    who: "Financial Crisis Inquiry Commission",
    title: "The Financial Crisis Inquiry Report",
    year: "2011",
    kind: "primary",
    url: "https://www.govinfo.gov/app/details/GPO-FCIC",
  },

  /* BIS / IMF / OECD / WTO */
  "bis-money-digital-age-2017": {
    id: "bis-money-digital-age-2017",
    who: "Morten Bech & Rodney Garratt (BIS)",
    title: "Central bank cryptocurrencies (Money in the digital age)",
    year: "2017",
    kind: "report",
    url: "https://www.bis.org/publ/qtrpdf/r_qt1709f.htm",
  },
  "bis-bank-capital-shocks-2018": {
    id: "bis-bank-capital-shocks-2018",
    who: "Bank for International Settlements",
    title: "The role of bank capital in the propagation of shocks",
    year: "2018",
    kind: "report",
    url: "https://www.bis.org/publ/work558.htm",
  },
  "imf-chicago-plan-revisited-2012": {
    id: "imf-chicago-plan-revisited-2012",
    who: "Jaromir Benes & Michael Kumhof (IMF)",
    title: "The Chicago Plan Revisited",
    year: "2012",
    kind: "report",
    url: "https://www.imf.org/external/pubs/cat/longres.aspx?sk=26178.0",
  },
  "bis-trade-finance-collapse-2009": {
    id: "bis-trade-finance-collapse-2009",
    who: "Bank for International Settlements",
    title: "Trade finance during the great trade collapse",
    year: "2009",
    kind: "report",
    url: "https://www.bis.org/publ/work297.htm",
  },
  "wto-auboin-restoring-trade-finance": {
    id: "wto-auboin-restoring-trade-finance",
    who: "Marc Auboin (WTO)",
    title: "Restoring Trade Finance During a Period of Financial Crisis",
    year: "2009",
    kind: "report",
    url: "https://www.wto.org/english/res_e/reser_e/ersd200916_e.htm",
  },
  "imf-institutional-view-capital-flows-2012": {
    id: "imf-institutional-view-capital-flows-2012",
    who: "International Monetary Fund",
    title: "The Liberalization and Management of Capital Flows — An Institutional View",
    year: "2012",
    kind: "primary",
    url: "https://www.imf.org/external/np/pp/eng/2012/111412.pdf",
  },
  "bis-sanctions-monetary-system-2023": {
    id: "bis-sanctions-monetary-system-2023",
    who: "Bank for International Settlements",
    title: "Sanctions and the international monetary system",
    year: "2023",
    kind: "report",
    url: "https://www.bis.org/publ/work1093.htm",
  },
  "oecd-pensions-at-a-glance": {
    id: "oecd-pensions-at-a-glance",
    who: "Organisation for Economic Co-operation and Development",
    title: "Pensions at a Glance",
    year: "biennial",
    kind: "report",
    url: "https://www.oecd.org/en/publications/oecd-pensions-at-a-glance_19991363.html",
  },
  "bis-crypto-tokens-defi-2023": {
    id: "bis-crypto-tokens-defi-2023",
    who: "Bank for International Settlements",
    title: "Crypto, tokens and DeFi: navigating the regulatory landscape",
    year: "2023",
    kind: "report",
    url: "https://www.bis.org/fsi/publ/insights49.htm",
  },

  /* NBER / AEA / JEP / JOLE */
  "sargent-ends-of-four-inflations-1982": {
    id: "sargent-ends-of-four-inflations-1982",
    who: "Thomas J. Sargent",
    title: "The Ends of Four Big Inflations (NBER volume chapter)",
    year: "1982",
    kind: "academic",
    url: "https://www.nber.org/books-and-chapters/inflation-causes-and-effects/ends-four-big-inflations",
  },
  "krugman-increasing-returns-trade-1979": {
    id: "krugman-increasing-returns-trade-1979",
    who: "Paul Krugman",
    title: "Increasing Returns, Monopolistic Competition, and International Trade",
    year: "1979",
    kind: "academic",
    url: "https://www.sciencedirect.com/science/article/abs/pii/0022199679900171",
  },
  "blanchard-public-debt-low-rates-2019": {
    id: "blanchard-public-debt-low-rates-2019",
    who: "Olivier Blanchard",
    title: "Public Debt and Low Interest Rates (AEA Presidential Address)",
    year: "2019",
    kind: "academic",
    url: "https://www.aeaweb.org/articles?id=10.1257/aer.109.4.1197",
  },
  "acemoglu-restrepo-tasks-automation-2022": {
    id: "acemoglu-restrepo-tasks-automation-2022",
    who: "Daron Acemoglu & Pascual Restrepo",
    title: "Tasks, Automation, and the Rise in U.S. Wage Inequality",
    year: "2022",
    kind: "academic",
    url: "https://www.nber.org/papers/w28920",
  },
  "brynjolfsson-productivity-jcurve-2019": {
    id: "brynjolfsson-productivity-jcurve-2019",
    who: "Erik Brynjolfsson, Daniel Rock & Chad Syverson",
    title: "The Productivity J-Curve",
    year: "2019",
    kind: "academic",
    url: "https://www.nber.org/papers/w25148",
  },
  "antras-deglobalisation-2020": {
    id: "antras-deglobalisation-2020",
    who: "Pol Antràs",
    title: "De-Globalisation? Global Value Chains in the Post-COVID-19 Age",
    year: "2020",
    kind: "academic",
    url: "https://www.nber.org/papers/w28115",
  },
  "froot-thaler-anomalies-fx-1990": {
    id: "froot-thaler-anomalies-fx-1990",
    who: "Kenneth A. Froot & Richard H. Thaler",
    title: "Anomalies: Foreign Exchange",
    year: "1990",
    kind: "academic",
    url: "https://www.aeaweb.org/articles?id=10.1257/jep.4.3.179",
  },

  /* Books with stable publisher URLs */
  "mehrling-money-interest-public-interest-1997": {
    id: "mehrling-money-interest-public-interest-1997",
    who: "Perry Mehrling",
    title: "The Money Interest and the Public Interest",
    year: "1997",
    kind: "academic",
    url: "https://www.worldcat.org/title/money-interest-and-the-public-interest/oclc/36418858",
  },
  "graeber-debt-5000-years-2011": {
    id: "graeber-debt-5000-years-2011",
    who: "David Graeber",
    title: "Debt: The First 5,000 Years",
    year: "2011",
    kind: "academic",
    url: "https://www.mhpbooks.com/books/debt/",
  },
  "bordo-eichengreen-bretton-woods-1993": {
    id: "bordo-eichengreen-bretton-woods-1993",
    who: "Michael D. Bordo & Barry Eichengreen (eds.)",
    title: "A Retrospective on the Bretton Woods System",
    year: "1993",
    kind: "academic",
    url: "https://www.nber.org/books-and-chapters/retrospective-bretton-woods-system-lessons-international-monetary-reform",
  },
  "brunnermeier-reserve-currency-2019": {
    id: "brunnermeier-reserve-currency-2019",
    who: "Markus K. Brunnermeier, Harold James & Jean-Pierre Landau",
    title: "The Digitalization of Money (reserve currency dynamics)",
    year: "2019",
    kind: "academic",
    url: "https://www.nber.org/papers/w26300",
  },
  "kirzner-competition-entrepreneurship-1973": {
    id: "kirzner-competition-entrepreneurship-1973",
    who: "Israel M. Kirzner",
    title: "Competition and Entrepreneurship",
    year: "1973",
    kind: "academic",
    url: "https://www.libertyfund.org/books/competition-and-entrepreneurship/",
  },
  "stiglitz-nobel-lecture-2001": {
    id: "stiglitz-nobel-lecture-2001",
    who: "Joseph E. Stiglitz",
    title: "Information and the Change in the Paradigm in Economics (Nobel Lecture)",
    year: "2001",
    kind: "academic",
    url: "https://www.nobelprize.org/prizes/economic-sciences/2001/stiglitz/lecture/",
  },
  "walzer-spheres-of-justice-1983": {
    id: "walzer-spheres-of-justice-1983",
    who: "Michael Walzer",
    title: "Spheres of Justice: A Defense of Pluralism and Equality",
    year: "1983",
    kind: "academic",
    url: "https://www.basicbooks.com/titles/michael-walzer/spheres-of-justice/9780465081899/",
  },
  "roth-who-gets-what-2015": {
    id: "roth-who-gets-what-2015",
    who: "Alvin E. Roth",
    title: "Who Gets What — and Why",
    year: "2015",
    kind: "academic",
    url: "https://www.gsb.stanford.edu/faculty-research/faculty/alvin-roth",
  },
  "titmuss-gift-relationship-1970": {
    id: "titmuss-gift-relationship-1970",
    who: "Richard M. Titmuss",
    title: "The Gift Relationship: From Human Blood to Social Policy",
    year: "1970",
    kind: "academic",
    url: "https://archive.org/details/giftrelationship0000titm",
  },
  "stiglitz-sen-fitoussi-mismeasuring-2010": {
    id: "stiglitz-sen-fitoussi-mismeasuring-2010",
    who: "Joseph E. Stiglitz, Amartya Sen & Jean-Paul Fitoussi",
    title: "Mismeasuring Our Lives: Why GDP Doesn't Add Up",
    year: "2010",
    kind: "academic",
    url: "https://thenewpress.com/books/mismeasuring-our-lives",
  },
  "sims-fiscal-theory-price-level": {
    id: "sims-fiscal-theory-price-level",
    who: "Christopher A. Sims",
    title: "Papers on the Fiscal Theory of the Price Level (homepage)",
    year: "various",
    kind: "academic",
    url: "http://sims.princeton.edu/",
  },
  "bernanke-gertler-watson-systematic-policy-1997": {
    id: "bernanke-gertler-watson-systematic-policy-1997",
    who: "Ben S. Bernanke, Mark Gertler & Mark Watson",
    title: "Systematic Monetary Policy and the Effects of Oil Price Shocks",
    year: "1997",
    kind: "academic",
    url: "https://www.brookings.edu/articles/systematic-monetary-policy-and-the-effects-of-oil-price-shocks/",
  },
  "pisani-ferry-geoeconomic-2022": {
    id: "pisani-ferry-geoeconomic-2022",
    who: "Jean Pisani-Ferry",
    title: "The geopolitical conundrum (geo-economic policy and supply chains)",
    year: "2022",
    kind: "report",
    url: "https://www.bruegel.org/people/jean-pisani-ferry",
  },
  "calvo-capital-market-crises-1998": {
    id: "calvo-capital-market-crises-1998",
    who: "Guillermo A. Calvo",
    title: "Capital Flows and Capital-Market Crises: The Simple Economics of Sudden Stops",
    year: "1998",
    kind: "academic",
    url: "https://www.jstor.org/stable/40325958",
  },
  "eichengreen-capital-flows-crises-2003": {
    id: "eichengreen-capital-flows-crises-2003",
    who: "Barry Eichengreen",
    title: "Capital Flows and Crises",
    year: "2003",
    kind: "academic",
    url: "https://mitpress.mit.edu/9780262550598/capital-flows-and-crises/",
  },
  "goodhart-evolution-central-banks-1988": {
    id: "goodhart-evolution-central-banks-1988",
    who: "Charles Goodhart",
    title: "The Evolution of Central Banks",
    year: "1988",
    kind: "academic",
    url: "https://mitpress.mit.edu/9780262570732/the-evolution-of-central-banks/",
  },
  "toniolo-cbcoop-bis-2005": {
    id: "toniolo-cbcoop-bis-2005",
    who: "Gianni Toniolo",
    title: "Central Bank Cooperation at the Bank for International Settlements, 1930-1973",
    year: "2005",
    kind: "academic",
    url: "https://www.cambridge.org/9780521845519",
  },
  "adrian-shin-liquidity-leverage-2010": {
    id: "adrian-shin-liquidity-leverage-2010",
    who: "Tobias Adrian & Hyun Song Shin",
    title: "Liquidity and Leverage (NY Fed Staff Report 328)",
    year: "2010",
    kind: "academic",
    url: "https://www.newyorkfed.org/research/staff_reports/sr328.html",
  },
  "smil-energy-transitions-2010": {
    id: "smil-energy-transitions-2010",
    who: "Vaclav Smil",
    title: "Energy Transitions: History, Requirements, Prospects",
    year: "2010",
    kind: "academic",
    url: "https://vaclavsmil.com/publications/",
  },
  "bnef-lcoe": {
    id: "bnef-lcoe",
    who: "BloombergNEF",
    title: "Levelized Cost of Electricity (LCOE) updates",
    year: "ongoing",
    kind: "report",
    url: "https://about.bnef.com/insights/clean-energy/lcoe/",
  },
  "lee-mason-population-aging-2011": {
    id: "lee-mason-population-aging-2011",
    who: "Ronald Lee & Andrew Mason (eds.)",
    title: "Population Aging and the Generational Economy (NTA project)",
    year: "2011",
    kind: "academic",
    url: "https://www.ntaccounts.org/",
  },
  "korinek-ai-economic-growth": {
    id: "korinek-ai-economic-growth",
    who: "Anton Korinek",
    title: "AI and economic growth (working papers)",
    year: "ongoing",
    kind: "academic",
    url: "https://www.brookings.edu/people/anton-korinek/",
  },
  "garratt-privacy-digital-money-2022": {
    id: "garratt-privacy-digital-money-2022",
    who: "Rodney Garratt",
    title: "Privacy and digital money (NY Fed-affiliated research)",
    year: "2022",
    kind: "academic",
    url: "https://www.newyorkfed.org/research/staff_reports/sr1041.html",
  },
  "dalio-big-debt-crises-2018": {
    id: "dalio-big-debt-crises-2018",
    who: "Ray Dalio",
    title: "Principles for Navigating Big Debt Crises",
    year: "2018",
    kind: "report",
    url: "https://economicprinciples.org/",
  },
  "shiller-long-run-data": {
    id: "shiller-long-run-data",
    who: "Robert J. Shiller",
    title: "Long-run U.S. stock market data (online dataset)",
    year: "ongoing",
    kind: "data",
    url: "http://www.econ.yale.edu/~shiller/data.htm",
  },
  "damodaran-asset-returns": {
    id: "damodaran-asset-returns",
    who: "Aswath Damodaran",
    title: "Annual asset returns and risk premia (online dataset)",
    year: "ongoing",
    kind: "data",
    url: "https://pages.stern.nyu.edu/~adamodar/",
  },
  "bridgewater-all-weather": {
    id: "bridgewater-all-weather",
    who: "Bridgewater Associates",
    title: "The All Weather Story",
    year: "1996–",
    kind: "report",
    url: "https://www.bridgewater.com/research-and-insights/the-all-weather-story",
  },
  "nar-existing-home-sales": {
    id: "nar-existing-home-sales",
    who: "National Association of Realtors",
    title: "Existing-Home Sales",
    year: "ongoing",
    kind: "data",
    url: "https://www.nar.realtor/research-and-statistics/housing-statistics/existing-home-sales",
  },
  "conference-board-lei": {
    id: "conference-board-lei",
    who: "The Conference Board",
    title: "U.S. Leading Economic Index",
    year: "ongoing",
    kind: "data",
    url: "https://www.conference-board.org/topics/us-leading-indicators",
  },
  "manheim-used-vehicle-index": {
    id: "manheim-used-vehicle-index",
    who: "Manheim / Cox Automotive",
    title: "Manheim Used Vehicle Value Index",
    year: "ongoing",
    kind: "data",
    url: "https://publish.manheim.com/en/services/consulting/used-vehicle-value-index.html",
  },
  "edmunds-true-cost-to-own": {
    id: "edmunds-true-cost-to-own",
    who: "Edmunds",
    title: "True Cost to Own (TCO) data",
    year: "ongoing",
    kind: "data",
    url: "https://www.edmunds.com/tco.html",
  },
  "bogle-international-equities-vanguard": {
    id: "bogle-international-equities-vanguard",
    who: "John C. Bogle (Vanguard)",
    title: "On hedging foreign equity exposure (Vanguard research)",
    year: "various",
    kind: "report",
    url: "https://corporate.vanguard.com/",
  },
  "aqr-style-premia": {
    id: "aqr-style-premia",
    who: "AQR Capital Management",
    title: "Style Premia research",
    year: "ongoing",
    kind: "report",
    url: "https://www.aqr.com/Insights/Research",
  },
  "greer-pimco-asset-class-1997": {
    id: "greer-pimco-asset-class-1997",
    who: "Robert J. Greer",
    title: "What is an Asset Class, Anyway?",
    year: "1997",
    kind: "academic",
    url: "https://www.pm-research.com/content/iijpormgmt/23/2/86",
  },
};

export function getSource(id: string): Source | null {
  return SOURCES[id] ?? null;
}

export function allSources(): Source[] {
  return Object.values(SOURCES);
}
